# Generated by Django 4.2.20 on 2025-04-29 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'unique_together': {('road_name', 'number', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Car Brand',
                'verbose_name_plural': 'Car Brands',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('email', models.EmailField(help_text='Client email, used for login.', max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(help_text='Unique driver name, used for login.', max_length=100, primary_key=True, serialize=False)),
                ('address', models.OneToOneField(help_text="Driver's unique address. Cannot delete address if a driver lives there.", on_delete=django.db.models.deletion.RESTRICT, related_name='driver_resident', to='taxi_rental_app.address')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ssn', models.CharField(help_text='SSN (XXX-XX-XXXX), used for login.', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='SSN must be in the format XXX-XX-XXXX', regex='^\\d{3}-\\d{2}-\\d{4}$')])),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField(help_text='Model identifier, unique within a car brand.')),
                ('color', models.CharField(max_length=40)),
                ('construction_year', models.SmallIntegerField(help_text='Year between 1900 and next year.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='taxi_rental_app.car')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'ordering': ['car__brand', 'model_id'],
                'unique_together': {('car', 'model_id')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id_within_driver', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 0 to 5.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to='taxi_rental_app.client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='taxi_rental_app.driver')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_date', models.DateField()),
                ('client', models.ForeignKey(help_text='Client who booked the rent. Cannot delete client if they have rents.', on_delete=django.db.models.deletion.RESTRICT, related_name='rents', to='taxi_rental_app.client')),
                ('driver', models.ForeignKey(help_text='Driver assigned to the rent. Cannot delete driver if they have rents.', on_delete=django.db.models.deletion.RESTRICT, related_name='rents', to='taxi_rental_app.driver')),
                ('model', models.ForeignKey(help_text='Model used for the rent. Cannot delete model if it has been used in rents.', on_delete=django.db.models.deletion.RESTRICT, related_name='rents', to='taxi_rental_app.model')),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
                'ordering': ['-rent_date', 'client__name'],
            },
        ),
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_rental_app.driver')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_rental_app.model')),
            ],
            options={
                'verbose_name': 'Driver Certification',
                'verbose_name_plural': 'Driver Certifications',
                'unique_together': {('driver', 'model')},
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='drives_models',
            field=models.ManyToManyField(related_name='drivers_certified', through='taxi_rental_app.Drives', to='taxi_rental_app.model'),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Card number must be 16 digits.', regex='^\\d{16}$')])),
                ('payment_addr', models.ForeignKey(help_text='Payment address for this card. Cannot delete address if used by card.', on_delete=django.db.models.deletion.RESTRICT, to='taxi_rental_app.address')),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_rental_app.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_rental_app.client')),
            ],
            options={
                'verbose_name': 'Client Address Link',
                'verbose_name_plural': 'Client Address Links',
                'unique_together': {('client', 'address')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='addresses',
            field=models.ManyToManyField(related_name='clients', through='taxi_rental_app.ClientAddress', to='taxi_rental_app.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_cards',
            field=models.ManyToManyField(related_name='client_owner', to='taxi_rental_app.creditcard'),
        ),
    ]
